CREATE DATABASE escola;
USE escola;
CREATE TABLE professor(
 id INT PRIMARY KEY AUTO_INCREMENT,
 nome VARCHAR(100) NOT NULL,
 email VARCHAR(100) NOT NULL
);
CREATE TABLE disciplina(
 id INT PRIMARY KEY AUTO_INCREMENT,
 nome VARCHAR(100) NOT NULL,
 carga_horaria INT NOT NULL,
 professor_id INT NOT NULL,
 FOREIGN KEY(professor_id) REFERENCES professor(id)
);